services:
  php-fpm:
    build:
      context: ..
      dockerfile: docker/php/Dockerfile
    container_name: vg-php
    environment:
      TZ: Europe/Amsterdam
    volumes:
      - ..:/app
    working_dir: /app
    expose:
      - "9000"

  nginx:
    image: nginx:alpine
    container_name: vg-nginx
    ports:
      - "8080:80"
    volumes:
      - ..:/app:ro
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - php-fpm
